config/routes.rb
Rails.application.routes.draw do
    root 'blogs#top'
    resources :sessions, only: [:new, :create, :destroy]
    resources :users, only: [:new, :create, :show]
    resources :favorites, only: [:create, :destroy]
    resources :blogs do
    collection do
        post :confirm
    end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
    validates :title, presence: true, length: { minimum: 1, maximum: 140 }
    validates :content, presence: true, length: { minimum: 1, maximum: 140 }
    mount_uploader :image, ImageUploader
     belongs_to :user
     has_many :favorites, dependent: :destroy
     has_many :favorite_users, through: :favorites, source: :user 
    # has_many :users, through: :favorites
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 30 } 
    validates :email, presence: true, length: { maximum: 255 },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_save { email.downcase! }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
    mount_uploader :image, ImageUploader
    has_many :favorites, dependent: :destroy
    has_many :blogs, dependent: :destroy
    has_many :favorite_blogs, through: :favorites, source: :blog
    # has_many :favorites, dependent: :destroy
    # has_many :favorite_blogs, through: :favorites,source: :blog
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
    before_action :set_blog, only: [:show, :edit, :update, :destroy]
    before_action :current_user_login, only: [:new, :edit, :show]
    def index
        @blogs = Blog.all
    end
    
    def new
        if params[:back]
        # @blog = Blog.new(blog_params)
        # else
        # @blog = Blog.new
        @blog = current_user.blogs.new(blog_params) 
        else
        @blog = current_user.blogs.new
        end
    end
    
    def create
        @blog = Blog.new(blog_params)
        @blog.user_id = current_user.id
        @blog.image.retrieve_from_cache! params[:cache][:image]
        # @blog.save!        
        #@blog = current_user.blogs.new(blog_params)
        if @blog.save
        ContactMailer.contact_mail(@blog).deliver 
        redirect_to new_blog_path
        else
        render 'new'
        end
    end
    

    def show
        @favorite = current_user.favorites.find_by(blog_id: @blog.id)
    end
    
    def edit
        @blog = Blog.find(params[:id])
    end
    
    def update
        @blog = Blog.find(params[:id])
        if @blog.update(blog_params)
            redirect_to blog_path, notice: "ブログを編集しました。"
        else
            render 'edit'
        end
    end
    
    def destroy
        @blog.destroy
        redirect_to blogs_path, notice:"削除完了"
    end
    
    def confirm
        @blog = current_user.blogs.new(blog_params)
        # render :new if @blog.invalid?
    end
    
    private
    
    def blog_params
        params.require(:blog).permit(:title, :content, :image, :image_cache)
    end
    
    def set_blog
        @blog = Blog.find(params[:id])
    end
    
    def current_user_login
        unless  current_user
        # flash[:referer] = 'ログインしてください'
        render new_session_path
        end
    end       
    
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログイン失敗'
      render 'new'
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウト"
    redirect_to new_session_path
  end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def show
        @user = User.find(params[:id])
        @favorite_blogs = @user.favorite_blogs
    end
    
    
    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to user_path(@user.id)
        else
            render 'new'
        end
    end
    
    
    private
    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
    def choose_new_or_edit
        if action_name == 'new' || action_name == 'confirm'
            confirm_blogs_path
        elsif action_name == 'edit'
            blog_path
        end
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    def logged_in?
        !current_user.nil?
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation"
     <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
         <% @blog.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="blog_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :blog_image %>
    <%= form.hidden_field :image_cache %>
  </div>
  
  <%= form.submit "ブログ投稿" %>
<% end %>
 
 <%= link_to "一覧表示に戻る", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  
  <p>タイトル：<%= @blog.title %></p>
  <p>本文：<%= @blog.content %></p>
  <%= image_tag(@blog.image.url) %>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <%= form.submit "登録する" %>
 <% end %>
 
 <%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: 'back' %>
 <% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local:true) do |form| %>
  <div class="blog_title">
      <%= form.label :title %>
      <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
 <% end %>

app/views/blogs/index.html.erb
<h1>一覧表示</h1>

<table>
    <tr>
        <th>タイトル</th>
        <th>内容</th>
    </tr>
    
    <% @blogs.each do |blog| %>
    <tr>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        
        <td><%= link_to '詳細', blog_path(blog.id), class: 'btn btn-default' %></td>
        <% if blog.user_id == current_user.id %>
            <td><%= link_to '編集', edit_blog_path(blog.id), class: 'btn btn-info' %></td>
            <td><%= link_to '削除', blog_path(blog.id), method: :delete, data: { confirm: '削除していいですか？' }, class: 'btn btn-danger' %></td>
        <% end %>
    </tr>
<% end %>



<% if false %>

<!--<%= image_tag(@blog.image.url) %>-->
<!--<%= image_tag @blog.image %>-->

<% end %>
</table>

<ul>
<li class="last"><%= link_to '投稿', new_blog_path %></li>
<li class="last"><%= link_to '一覧表示', blogs_path %></li>
</ul>

app/views/blogs/new.html.erb
<h2>新規投稿</h2>
<%= render 'form' %>

app/views/blogs/show.html.erb
<h1>詳細確認</h1>
<p>投稿者名：<%= @blog.user.name %></p>
<p>タイトル：<%= @blog.title %></p>
<p>内容：<%= @blog.content %></p>
<p>写真：<%= image_tag @blog.image %></p>
<%= link_to '一覧表示', blogs_path %>


<% unless @blog.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/blogs/top.html.erb
  <div>
  <h1>TWEETページ</h1>
  <img src="/header.jpg" class="logo_image">    
    <div class="container">
        <div class="row">
            <nav class="menu">
            <div class="col-md-12">
                <!--<ul class="row_A">-->
                <!--    <li class="col-sm-10 col-md-6"><h2> 日常のつぶやきを集めます。</h2></class></li>-->
                <!--    <li class="col-sm-2 col-md-6" ><a class="btn" href="/blogs">一覧確認</a></li>-->
        
                <!--</ul>-->
            </div>
            </nav>
            
            <nav class="menu">
            <div class="col-md-12">
                <!--<ul class="row_B">-->
                <!--    <li class="col-sm-10 col-md-6"><h2>つぶやきます。</h2></li>-->
                <!--    <li class="col-sm-2 col-md-6"><a class="btn" href="/blogs/new">新規投稿</a></li>-->
                <!--</ul>-->
            </div>
            </nav>
        </div>
    </div>
    <p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kadai2</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--<header class="header">-->
    <!--  <ul>-->
    <!--    <li><a class="top" href="/">TOP</a></li>-->
    <!--  </ul>-->
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <% if logged_in? %>
      <%= link_to "一覧表示", blogs_path(current_user.id) %>
      <%= link_to "お気に入り一覧", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "初めての新規登録", new_user_path %>
      <%= link_to "ログイン", new_session_path %>
    <% end %>

    </header>
    
    <%= yield %>
    
    <footer class="footer">
      <p>2017年10月期生</p>
      <p>2015-2016 Copyright DIVE INTO CODE Corp.</p>
    </footer>
    
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email, id: :user_email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password, id: :user_password %>
  </div>
  
  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :user_password %>
  </div>
  
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :user_image %>
    <%= form.hidden_field :image_cache %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>初めての新規登録</h1>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %>prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.label :image %>
  <%= f.file_field :image, id: :feed_image %>
  <%= f.hidden_field :image_cache %>

  
  <%= f.submit "ユーザー登録" %>
<% end %>

app/views/users/show.html.erb
<h3>ユーザー<%= @user.name %>のお気に入りページ</h3>

<%= image_tag @user.image %>


<p>メールアドレス：<%= @user.email %></p>

<h2>お気に入り</h2>
<% @user.favorite_blogs.each do |blog| %>
<ol>
    <li>タイトル：<%= blog.title %>内容：<%= blog.content %></li>
</ol>


<% end %>